server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: customer-service
  config:
    import:
      - vault://
      - configserver:http://localhost:8888

  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_TOKEN:your-vault-token}
      kv:
        enabled: true
        backend: secret
        default-context: ${spring.application.name}/dev
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}
      fail-fast: true



#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
##
##
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    generate-ddl: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/dmc


