server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: customer-service
  config:
    import:
      - vault://secret/customer-service/dev
      - configserver:http://localhost:8888

  cloud:
    vault:
      uri: http://localhost:8200
      token: hvs.5iAR19YDb4yZrXmp2U69xjjP
      kv:
        enabled: true
        backend: secret
        application-name: customer-service
    config:
      username: ${config_username:${CONFIG_USERNAME:admin}}
      password: ${config_password:${CONFIG_PASSWORD:admin}}
      fail-fast: true



#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
##
##
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    generate-ddl: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/dmc


